"""empty message

Revision ID: 53cf2b41ca48
Revises: de36186a051d
Create Date: 2019-08-05 13:54:29.804559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cf2b41ca48'
down_revision = 'de36186a051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
